# Generated by Django 5.2.5 on 2025-08-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Day',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
